/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
}

dependencies{
    implementation("org.assertj:assertj-core:3.22.0")
}

repositories{
    mavenCentral()
}